apiVersion: v1
kind: Service
metadata:
  name: link-shortener
  labels:
    app: link-shortener
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: link-shortener
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: link-shortener
data:
  hibernate_dll-auto: create 
---
apiVersion: v1
kind: Secret
metadata:
  name: link-shortener
type: Opaque
data:
  client_id: bGluay1zaG9ydGVuZXI=
  client_secret: cGFzc3dvcmQ=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-shortener
  labels:
    app: link-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: link-shortener
  template:
    metadata:
      labels:
        app: link-shortener
    spec:
      containers:
      - name: link-shortener
        image: link-shortener
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: database-name
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-password
        - name: HIBERNATE_DLL-AUTO
          valueFrom:
            configMapKeyRef:
              name: link-shortener
              key: hibernate_dll-auto
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: link-shortener
              key: client_id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: link-shortener
              key: client_secret