apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb
data:
  database-name: link-shortener
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
data:
  database-password: UGlvdF8xMjM=
  database-user: cGlvdHI=