apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-auth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
               name: postgres-auth
               key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
               name: postgres-auth
               key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
               name: postgres-auth
               key: POSTGRES_PASSWORD
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-auth-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
  labels:
    app: postgres-auth
spec:
  type: NodePort
  ports:
   - port: 5432
     protocol: TCP
  selector:
   app: postgres-auth