apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-auth
  labels:
    app: postgres-auth
data:
  POSTGRES_DB: authdb
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=